import React, { PropTypes } from 'react';
import ReactBlocklyComponent from 'react-blockly-component';
import { blocklyXmlToRoboAst } from '../core/blockly';
import { generateBlocklyXml } from '../core/blocklyXmlGenerator';
import { completeToolbox } from '../core/toolbox';


const workspaceConfiguration = {
  trashcan: true,
};


// Blockly editor requires global Blockly object
// It fills the parent div completely and resize on dimensions change
export default class BlocklyEditor extends React.Component {

  // ReactBlocklyComponent only sets an initial XML. However, we need to change
  // it externally sometimes (for example, when a new task is set). Thus, we
  // need to set new BlocklyXml manually.
  // To avoid infinite update-dispatch loop, we can only set new xml if it has
  // changed. Note that we can't compare ASTs, because they contain blockIDs,
  // which are generated by Blockly internally and so they are different for
  // same XMLs).
  componentDidUpdate(prevProps) {
    const prevXml = generateBlocklyXml(prevProps.roboAst);
    const currentXml = generateBlocklyXml(this.props.roboAst);
    if (prevXml !== currentXml) {
      this.setXml(currentXml);
    }
  }

  setXml(xml) {
    this.blocklyWorkspace.clear();
    this.blocklyEditor.importFromXml(xml);
  }

  // Return Blockly.Workspace
  // (node_modules/node-blockly/blockly/core/workspace.js)
  get blocklyWorkspace() {
    return this.workspaceComponent.state.workspace;
  }

  // Return ReactBlocklyComponent.BlocklyWorkspace
  // (node_modules/react-blockly-component/src/BlocklyWorkspace.jsx)
  get workspaceComponent() {
    return this.blocklyEditor.refs.workspace;
  }

  render() {
    const initialXml = generateBlocklyXml(this.props.roboAst);
    const xmlDidChange = newXml => {
      const roboAst = blocklyXmlToRoboAst(newXml);
      this.props.onChange(roboAst);
    };
    return (
      <div
        style={{
          display: 'inline-block',
          position: 'absolute',
          top: '0px',
          bottom: '0px',
          left: '0px',
          right: '0px',
          color: 'green',
        }}
      >
        <ReactBlocklyComponent.BlocklyEditor
          ref={(ref) => { this.blocklyEditor = ref; }}
          workspaceConfiguration={workspaceConfiguration}
          toolboxBlocks={this.props.toolboxBlocks}
          initialXml={initialXml}
          xmlDidChange={xmlDidChange}
          wrapperDivClassName={'fill-height'}
        />
      </div>
    );
  }
}

BlocklyEditor.propTypes = {
  toolboxBlocks: PropTypes.array,
  roboAst: PropTypes.object,
  onChange: PropTypes.func,
};

BlocklyEditor.defaultProps = {
  toolboxBlocks: completeToolbox,
  roboAst: { head: 'start', body: [] },
  onChange: null,
};
